version: '2'

services:
  spark:
    image: bitnami/spark:3.0.1
    hostname: spark
    container_name: spark_master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
    volumes:
      - D:/Archivos_uni/TFM/TFMDataLake/target:/home/datalake
      - D:/Archivos_uni/TFM/dataset/data:/data
  spark-worker-1:
    image: bitnami/spark:3.0.1
    container_name: spark_worker_1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - D:/Archivos_uni/TFM/TFMDataLake/target:/home/datalake
      - D:/Archivos_uni/TFM/dataset/data:/data
  spark-worker-2:
    image: bitnami/spark:3.0.1
    container_name: spark_worker_2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - D:/Archivos_uni/TFM/TFMDataLake/target:/home/datalake
      - D:/Archivos_uni/TFM/dataset/data:/data
  spark-submit-kafkareaderwriter:
    image: bitnami/spark:3.0.1
    command: /opt/bitnami/spark/bin/spark-submit --class org.tfmupm.KafkaReaderWriterDocker /home/datalake/TFMDataLake-1.0-SNAPSHOT.jar
    volumes:
      - D:/Archivos_uni/TFM/TFMDataLake/target:/home/datalake
  spark-submit-tablereader:
    image: bitnami/spark:3.0.1
    command: /opt/bitnami/spark/bin/spark-submit --class org.tfmupm.ambulatoryReaderDocker /home/datalake/TFMDataLake-1.0-SNAPSHOT.jar
    volumes:
      - D:/Archivos_uni/TFM/TFMDataLake/target:/home/datalake
  nifi:
    image: apache/nifi:latest
    ports:
      - "8081:8080"
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "nifitopic:1:1,nificontinuous:1:1"

  jupyter:
    image: jupyter/base-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - D:/Archivos_uni/TFM/TFMDataLake/target:/home/datalake
    command: start-notebook.sh --NotebookApp.token=''